import type { ReportArtifact, SlackBlock, SlackPayload } from "@/lib/vector/types"

const BULLET = "\u2022"

function sectionBlock(text: string): SlackBlock {
  return {
    type: "section",
    text: { type: "mrkdwn", text },
  }
}

function dividerBlock(): SlackBlock {
  return { type: "divider" }
}

export function renderBlockkitPreview(artifact: ReportArtifact): SlackPayload {
  const visibleSections = artifact.sections.filter(
    (section) => section.id !== "sec-hypotheses" && section.id !== "sec-recommendations"
  )

  const hypothesisLines = artifact.hypotheses.map(
    (hypothesis) => `${BULLET} *[${hypothesis.confidence.toUpperCase()}]* ${hypothesis.claim}`
  )
  const recommendationLines = artifact.recommendations.map(
    (recommendation, index) =>
      `${index + 1}. *${recommendation.title}* \u2014 ${recommendation.owner}, ${recommendation.eta}`
  )

  const blocks: SlackBlock[] = [
    {
      type: "header",
      text: { type: "plain_text", text: "Weekly Product Brief" },
    },
    sectionBlock(`*Reporting Window*\n${artifact.periodLabel}`),
    dividerBlock(),
    ...visibleSections.flatMap((section) => [
      sectionBlock(`*${section.title}*\n${section.content}`),
      dividerBlock(),
    ]),
    sectionBlock(`*Hypotheses*\n${hypothesisLines.join("\n")}`),
    dividerBlock(),
    sectionBlock(`*Recommendations*\n${recommendationLines.join("\n")}`),
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `Generated by Vector \u2022 Artifact ${artifact.id}`,
        },
      ],
    },
  ]

  return {
    text: `Weekly Product Brief (${artifact.periodLabel})`,
    blocks,
  }
}
